name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build:
    name: Build and test on latest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: 'Sanity check'
        run: |
          ls
