name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: rainlabs-eu/cmake-quality-action@v1.0.0-alpha
