name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build:
    name: Build and test on latest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          path: source
          submodules: true
      - name: 'CMake Configure'
        run: |
          cmake -S source/ -B build/
