name: CMake Quality Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: rainlabs-eu/cmake-quality-action@master
        with:
          cmake_configure_environemnt: "CC=clang-9 CXX=clang++9"
