name: CMake Quality Check

on: [push, pull_request]

jobs:
  build:
    name: "Build and Test"
    strategy:
      fail-fast: false
      matrix:
        cmake_environment:
          [
            "CC=clang-6.0 CXX=clang++-6.0",
            "CC=clang-7 CXX=clang++-7",
            "CC=clang-8 CXX=clang++-8",
            "CC=clang-9 CXX=clang++-9",
            "CC=gcc-6 CXX=g++-6",
            "CC=gcc-7 CXX=g++-7",
            "CC=gcc-8 CXX=g++-8",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: rainlabs-eu/ghaction-cmake-quality@master
        with:
          cmake_configure_environment: ${{ matrix.cmake_environment }}
